apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  mysql-root-password: rootpassword
  mysql-password: wppassword



#UPDATE wp_users 
#SET user_pass = MD5('nuovapassword') 
#WHERE user_login = 'user';


#UPDATE wp_usermeta 
#SET meta_value = 'a:1:{s:13:"administrator";b:1;}'
#WHERE user_id = 1 AND meta_key = 'wp_capabilities';


#UPDATE wp_usermeta 
#SET meta_value = '10'
#WHERE user_id = 1 AND meta_key = 'wp_user_level';
